language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python test_python.py # or py.test for Python versions 3.5 and below
